INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Robert Davis', 'user_93756@example.com', '+1-870-901-9586', 'Robert', 'Davis', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "850832"}, NULL, NULL, 'USD', 3000.4096, 72.6895, 195.6063, false, true, True, False, True, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Davis, Robert', 'https://api.dicebear.com/7.x/big-smile/svg', NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('John Jones', 'user_11671@example.com', '+1-179-864-6609', 'John', 'Jones', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 4615.4202, 60.7838, 139.3595, false, true, False, True, True, true, false, true, true, VID_27155, NULL, NULL, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Jones, John', 'https://api.dicebear.com/7.x/croodles/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('James Jones', 'user_31622@example.com', '+1-648-445-3974', 'James', 'Jones', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 5650.9157, 93.4762, 145.5552, false, true, True, True, False, true, false, true, true, VID_13747, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Jones, James', 'https://api.dicebear.com/7.x/open-peeps/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jennifer Brown', 'user_71302@example.com', '+1-603-272-5511', 'Jennifer', 'Brown', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "227260"}, NULL, NULL, 'USD', 6635.4403, 79.6799, 105.0494, false, true, True, True, True, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Brown, Jennifer', 'https://api.dicebear.com/7.x/thumbs/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Michael Johnson', 'user_55659@example.com', '+1-137-495-5400', 'Michael', 'Johnson', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 3620.2348, 43.7766, 151.9796, false, true, False, False, True, true, false, true, true, VID_73796, NULL, NULL, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Johnson, Michael', 'https://api.dicebear.com/7.x/avataaars/svg', NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Michael Smith', 'user_46235@example.com', '+1-407-573-2088', 'Michael', 'Smith', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "371336"}, NULL, NULL, 'USD', 5567.773, 1.3952, 115.6522, false, true, True, False, True, true, false, true, true, NULL, NULL, NULL, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Smith, Michael', 'https://api.dicebear.com/7.x/adventurer/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jennifer Garcia', 'user_90532@example.com', '+1-125-151-9512', 'Jennifer', 'Garcia', 'Ima Dummy', This is a sample biography., NULL, NULL, NULL, 'USD', 1533.8323, 87.6487, 113.2623, false, true, False, False, True, true, false, true, true, VID_60978, NULL, NULL, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Garcia, Jennifer', 'https://api.dicebear.com/7.x/bottts/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Linda Williams', 'user_12453@example.com', '+1-373-802-5891', 'Linda', 'Williams', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "125559"}, NULL, NULL, 'USD', 2548.2856, 2.519, 174.8419, false, true, True, False, True, true, false, true, true, NULL, NULL, NULL, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Williams, Linda', 'https://api.dicebear.com/7.x/micah/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('William Brown', 'user_18616@example.com', '+1-828-556-4646', 'William', 'Brown', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 3843.7897, 1.3821, 101.2412, false, true, False, True, False, true, false, true, true, NULL, NULL, NULL, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Brown, William', 'https://api.dicebear.com/7.x/personas/svg', NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Michael Brown', 'user_94390@example.com', '+1-582-316-7995', 'Michael', 'Brown', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "714194"}, NULL, NULL, 'USD', 1948.7601, 46.2894, 149.7981, false, true, True, True, False, true, false, true, true, NULL, NULL, NULL, '2024-03-04 11:26:25');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Brown, Michael', 'https://api.dicebear.com/7.x/thumbs/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
