INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jennifer Smith', 'user_41701@example.com', '+1-189-907-5528', 'Jennifer', 'Smith', 'Ima Dummy', This is a sample biography., NULL, NULL, NULL, 'USD', 8364.8194, 92.1658, 199.0814, false, true, True, False, False, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Smith, Jennifer', http://example.com/image_542286.jpg, NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Michael Brown', 'user_69435@example.com', '+1-593-343-7938', 'Michael', 'Brown', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "584773"}, NULL, NULL, 'USD', 2018.7332, 71.4235, 110.9183, false, true, True, True, False, true, false, true, true, VID_93237, NULL, NULL, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Brown, Michael', http://example.com/image_249235.jpg, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jennifer Miller', 'user_32597@example.com', '+1-242-245-9198', 'Jennifer', 'Miller', 'Ima Dummy', This is a sample biography., NULL, NULL, NULL, 'USD', 4958.8781, 7.3966, 124.0937, false, true, False, True, True, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Miller, Jennifer', NULL, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('William Garcia', 'user_20388@example.com', '+1-524-735-8484', 'William', 'Garcia', 'Ima Dummy', This is a sample biography., NULL, NULL, NULL, 'USD', 6901.847, 44.105, 199.0608, false, true, True, False, True, true, false, true, true, NULL, NULL, NULL, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Garcia, William', NULL, NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('William Brown', 'user_94230@example.com', '+1-648-493-4102', 'William', 'Brown', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "294628"}, NULL, NULL, 'USD', 9232.2335, 9.6716, 144.0173, false, true, True, True, False, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Brown, William', http://example.com/image_881619.jpg, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('John Williams', 'user_48215@example.com', '+1-151-914-7999', 'John', 'Williams', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 9463.8094, 28.4, 141.7672, false, true, True, True, True, true, false, true, true, VID_36212, NULL, NULL, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Williams, John', NULL, NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jane Rodriguez', 'user_66463@example.com', '+1-427-558-7979', 'Jane', 'Rodriguez', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 133.3114, 43.2566, 180.8483, false, true, False, False, False, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Rodriguez, Jane', NULL, NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jennifer Davis', 'user_96270@example.com', '+1-653-769-2110', 'Jennifer', 'Davis', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "110601"}, NULL, NULL, 'USD', 4899.1279, 24.0069, 169.0776, false, true, True, True, False, true, false, true, true, VID_20549, NULL, NULL, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Davis, Jennifer', NULL, NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Michael Martinez', 'user_92295@example.com', '+1-869-778-3543', 'Michael', 'Martinez', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "684477"}, NULL, NULL, 'USD', 5655.598, 42.5964, 102.2923, false, true, True, True, False, true, false, true, true, NULL, NULL, NULL, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Martinez, Michael', NULL, NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jane Garcia', 'user_41106@example.com', '+1-737-224-8015', 'Jane', 'Garcia', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 8073.7442, 90.1775, 164.1292, false, true, False, False, False, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 10:29:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Garcia, Jane', NULL, NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
