INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Mary Jones', 'user_14097@example.com', '+1-159-244-4178', 'Mary', 'Jones', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "401696"}, NULL, NULL, 'USD', 4005.8458, 73.1166, 169.5941, false, true, True, False, False, true, false, true, true, VID_41986, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Jones, Mary', 'https://api.dicebear.com/7.x/big-ears/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Mary Martinez', 'user_30212@example.com', '+1-690-873-9446', 'Mary', 'Martinez', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "703465"}, NULL, NULL, 'USD', 9228.8893, 96.7372, 116.4617, false, true, False, True, True, true, false, true, true, VID_40294, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Martinez, Mary', 'https://api.dicebear.com/7.x/open-peeps/svg', NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Mary Williams', 'user_21863@example.com', '+1-282-114-1171', 'Mary', 'Williams', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "637222"}, NULL, NULL, 'USD', 2663.7946, 92.1479, 162.4261, false, true, True, True, True, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Williams, Mary', 'https://api.dicebear.com/7.x/bottts/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Linda Brown', 'user_60747@example.com', '+1-467-228-1227', 'Linda', 'Brown', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 1937.5076, 3.3361, 127.327, false, true, True, True, False, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Brown, Linda', 'https://api.dicebear.com/7.x/avataaars/svg', NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('William Williams', 'user_30510@example.com', '+1-825-499-8553', 'William', 'Williams', 'Ima Dummy', This is a sample biography., NULL, NULL, NULL, 'USD', 3145.1824, 99.7139, 170.7958, false, true, True, True, True, true, false, true, true, VID_12544, NULL, NULL, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Williams, William', 'https://api.dicebear.com/7.x/notionists/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Mary Rodriguez', 'user_48481@example.com', '+1-697-810-4276', 'Mary', 'Rodriguez', 'Ima Dummy', This is a sample biography., NULL, NULL, NULL, 'USD', 805.2156, 4.4644, 178.2091, false, true, True, True, True, true, false, true, true, VID_30865, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Rodriguez, Mary', 'https://api.dicebear.com/7.x/lorelei/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jane Brown', 'user_15822@example.com', '+1-239-408-1951', 'Jane', 'Brown', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "495966"}, NULL, NULL, 'USD', 5289.3002, 49.4718, 178.4771, false, true, True, False, False, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Brown, Jane', 'https://api.dicebear.com/7.x/croodles/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Patricia Williams', 'user_89216@example.com', '+1-968-974-6400', 'Patricia', 'Williams', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "602302"}, NULL, NULL, 'USD', 1180.1833, 72.6074, 167.0537, false, true, True, False, False, true, false, true, true, VID_86336, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Williams, Patricia', 'https://api.dicebear.com/7.x/avataaars/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Patricia Miller', 'user_21576@example.com', '+1-195-649-3891', 'Patricia', 'Miller', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "329659"}, NULL, NULL, 'USD', 9701.706, 61.278, 164.1157, false, true, False, False, True, true, false, true, true, NULL, NULL, NULL, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Miller, Patricia', 'https://api.dicebear.com/7.x/bottts/svg', NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('James Williams', 'user_71079@example.com', '+1-705-783-2682', 'James', 'Williams', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "218022"}, NULL, NULL, 'USD', 9882.984, 40.6345, 142.1567, false, true, True, True, True, true, false, true, true, VID_55773, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-04 11:28:52');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Williams, James', 'https://api.dicebear.com/7.x/croodles/svg', {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
