INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Mary Miller', 'user_15584@example.com', '+1-290-833-5661', 'Mary', 'Miller', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "788629"}, NULL, NULL, 'USD', 3554.4515, 47.8061, 142.1026, false, true, True, True, True, true, false, true, true, VID_90194, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_528186', NULL, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jane Martinez', 'user_76618@example.com', '+1-550-535-3209', 'Jane', 'Martinez', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 9194.3739, 10.4092, 188.6805, false, true, False, False, True, true, false, true, true, VID_97833, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_989466', http://example.com/image_677642.jpg, NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('William Brown', 'user_38690@example.com', '+1-648-683-7965', 'William', 'Brown', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "259169"}, NULL, NULL, 'USD', 705.2927, 20.6537, 103.9834, false, true, True, True, True, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_587704', http://example.com/image_453612.jpg, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Robert Rodriguez', 'user_26362@example.com', '+1-889-806-5723', 'Robert', 'Rodriguez', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "106215"}, NULL, NULL, 'USD', 4149.0728, 25.3993, 143.4574, false, true, True, True, False, true, false, true, true, VID_29384, NULL, NULL, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_360414', NULL, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Patricia Jones', 'user_27162@example.com', '+1-560-970-5608', 'Patricia', 'Jones', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 5523.6207, 0.2669, 169.9669, false, true, True, True, False, true, false, true, true, VID_94415, NULL, NULL, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_804699', NULL, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('William Davis', 'user_48997@example.com', '+1-619-535-7180', 'William', 'Davis', 'Ima Dummy', This is a sample biography., NULL, NULL, NULL, 'USD', 4037.4297, 44.804, 192.4499, false, true, True, False, False, true, false, true, true, NULL, NULL, NULL, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_916021', NULL, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Linda Miller', 'user_66793@example.com', '+1-784-627-8855', 'Linda', 'Miller', 'Ima Dummy', NULL, {"bank": "Bank Name", "account": "141348"}, NULL, NULL, 'USD', 5388.7065, 50.2769, 192.8854, false, true, True, True, True, true, false, true, true, VID_91058, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_781617', NULL, NULL, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jane Jones', 'user_74545@example.com', '+1-922-831-1526', 'Jane', 'Jones', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 2483.0046, 27.4922, 160.3364, false, true, True, True, False, true, false, true, true, NULL, NULL, {"rec1": "Good", "rec2": "Excellent"}, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_670275', NULL, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('Jane Williams', 'user_10455@example.com', '+1-153-665-2651', 'Jane', 'Williams', 'Ima Dummy', This is a sample biography., {"bank": "Bank Name", "account": "224680"}, NULL, NULL, 'USD', 7056.1258, 87.6223, 195.6849, false, true, True, True, True, true, false, true, true, NULL, NULL, NULL, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_547345', http://example.com/image_628489.jpg, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
INSERT INTO user (legalName, email, phoneNumber, firstName, lastName, stageName, biography, bankingData, primaryProfileId, primaryCreativeId, currency, currentBalance, fromRate, toRate, isArtist, isCreative, isNegotiable, isIDVerified, isSocialVerified, isActive, isDeactivated, allowSms, termsApproved, IDVid, careerMode, recommendations, createdDate) VALUES ('John Johnson', 'user_24847@example.com', '+1-713-796-8757', 'John', 'Johnson', 'Ima Dummy', NULL, NULL, NULL, NULL, 'USD', 5996.2861, 35.6429, 106.9781, false, true, True, True, False, true, false, true, true, NULL, NULL, NULL, '2024-03-01 17:28:02');
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO creative (name, imageURL, creativeData, userId) VALUES ('Creative_607847', http://example.com/image_698351.jpg, {"type": "Art", "description": "Sample creative data"}, NULL);
SET @last_creative_id = LAST_INSERT_ID();
UPDATE user SET primaryCreativeId = @last_creative_id WHERE id = @last_user_id;
UPDATE creative SET userId = @last_user_id WHERE id = @last_creative_id;
